"""Tests for the snake playfield, cycle construction and route planner.

The planner's two claims -- it never traps itself, and it eats everything -- are the reason
this design was chosen over A*-with-tail-following.  They are asserted here rather than
trusted, including under randomised input, because the failure mode is a silently broken
README regenerated by a cron nobody is watching.
"""

from __future__ import annotations

import collections
import datetime as dt
import random
import re
import sys
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

from profilegen.snake import ai, grid, render
from profilegen.snake.hamilton import (
    adjacent,
    cycle_order,
    hamiltonian_cycle,
)


class HamiltonianCycleTests(unittest.TestCase):
    def test_covers_every_cell_exactly_once(self) -> None:
        cycle = hamiltonian_cycle(52, 7)
        self.assertEqual(len(cycle), 52 * 7)
        self.assertEqual(len(set(cycle)), 52 * 7)

    def test_consecutive_cells_are_adjacent_and_it_closes(self) -> None:
        cycle = hamiltonian_cycle(52, 7)
        for index in range(len(cycle)):
            self.assertTrue(
                adjacent(cycle[index], cycle[(index + 1) % len(cycle)]),
                f"gap between {cycle[index]} and {cycle[(index + 1) % len(cycle)]}",
            )

    def test_holds_across_many_even_area_grids(self) -> None:
        for width in range(2, 21):
            for height in range(2, 21):
                if (width * height) % 2:
                    continue
                with self.subTest(width=width, height=height):
                    cycle = hamiltonian_cycle(width, height)
                    self.assertEqual(len(set(cycle)), width * height)
                    for index in range(len(cycle)):
                        self.assertTrue(
                            adjacent(cycle[index], cycle[(index + 1) % len(cycle)])
                        )

    def test_odd_area_is_rejected_loudly(self) -> None:
        # 53x7 is the real contribution calendar, and it provably has no cycle.
        for width, height in ((53, 7), (3, 3), (5, 7)):
            with self.subTest(width=width, height=height):
                with self.assertRaises(ValueError):
                    hamiltonian_cycle(width, height)

    def test_cycle_order_is_a_bijection(self) -> None:
        cycle = hamiltonian_cycle(12, 6)
        order = cycle_order(cycle)
        self.assertEqual(sorted(order.values()), list(range(len(cycle))))


def _days(dates: dict[str, int], *, year: int = 2026) -> list[dict]:
    return [{"date": date, "count": count, "level": min(4, count)} for date, count in dates.items()]


class PlayfieldTests(unittest.TestCase):
    def test_dimensions_are_the_cropped_even_grid(self) -> None:
        field = grid.build(_days({"2026-05-01": 3}), today=dt.date(2026, 9, 14))
        self.assertEqual((field.cols, field.rows), (52, 7))
        self.assertEqual(len(field.levels), 52)
        self.assertTrue(all(len(column) == 7 for column in field.levels))

    def test_targets_are_exactly_the_nonzero_days(self) -> None:
        field = grid.build(
            _days({"2026-05-01": 3, "2026-05-02": 0, "2026-06-10": 1}),
            today=dt.date(2026, 9, 14),
        )
        self.assertEqual(len(field.targets), 2)
        self.assertEqual(field.total, 4)

    def test_future_days_are_dropped(self) -> None:
        # The tokenless endpoint returns the whole calendar year, so a September run sees
        # months of empty future.  Anchoring on `today` is what keeps the board current.
        field = grid.build(
            _days({"2026-05-01": 2, "2026-12-30": 9}), today=dt.date(2026, 9, 14)
        )
        self.assertEqual(field.total, 2)
        self.assertEqual(len(field.targets), 1)
        self.assertEqual(field.last_date, "2026-09-14")

    def test_empty_input_yields_an_empty_field(self) -> None:
        field = grid.build([])
        self.assertEqual(field.total, 0)
        self.assertEqual(field.targets, ())


class PlannerTests(unittest.TestCase):
    def _field(self, targets: list[tuple[int, int]], cols: int = 52, rows: int = 7):
        levels = [[0] * rows for _ in range(cols)]
        counts = [[0] * rows for _ in range(cols)]
        for col, row in targets:
            levels[col][row] = 2
            counts[col][row] = 2
        return grid.Playfield(
            cols=cols,
            rows=rows,
            levels=tuple(tuple(c) for c in levels),
            counts=tuple(tuple(c) for c in counts),
            targets=tuple(targets),
            total=2 * len(targets),
            first_date="2025-09-21",
            last_date="2026-09-14",
        )

    def _assert_run_is_valid(self, record) -> None:
        for step in range(record.steps + 1):
            length = record.length_at(step)
            segments = [record.segment_at(step, i) for i in range(length)]
            self.assertEqual(
                len(set(segments)), length, f"self-collision at step {step}"
            )
            for a, b in zip(segments, segments[1:]):
                self.assertTrue(
                    adjacent(a, b), f"body broke apart at step {step}: {a} -> {b}"
                )
            for col, row in segments:
                self.assertTrue(0 <= col < record.cols and 0 <= row < record.rows)

    def test_eats_everything_without_trapping_itself(self) -> None:
        targets = [(3, 1), (10, 5), (25, 0), (40, 6), (51, 3)]
        record = ai.plan(self._field(targets))
        self.assertEqual({(m.col, m.row) for m in record.meals}, set(targets))
        self._assert_run_is_valid(record)

    def test_length_grows_by_exactly_one_per_meal(self) -> None:
        targets = [(2, 2), (7, 4), (19, 1), (33, 6)]
        record = ai.plan(self._field(targets))
        self.assertEqual(record.max_length, record.start_length + len(targets))
        for index, (_step, length) in enumerate(record.growth):
            self.assertEqual(length, record.start_length + index + 1)

    def test_track_prefix_keeps_segment_indices_in_range(self) -> None:
        record = ai.plan(self._field([(5, 5), (30, 2)]))
        self.assertEqual(record.start_offset, record.start_length - 1)
        # The invariant the renderer relies on: index never goes negative at step 0.
        self.assertGreaterEqual(record.start_offset - (record.start_length - 1), 0)

    def test_randomised_stress_over_many_target_sets(self) -> None:
        rng = random.Random(20260914)
        cells = [(c, r) for c in range(52) for r in range(7)]
        for trial in range(25):
            targets = sorted(rng.sample(cells, 30))
            with self.subTest(trial=trial):
                record = ai.plan(self._field(targets))
                self.assertEqual({(m.col, m.row) for m in record.meals}, set(targets))
                self._assert_run_is_valid(record)

    def test_is_deterministic(self) -> None:
        field = self._field([(4, 4), (22, 0), (47, 6)])
        self.assertEqual(ai.plan(field).track, ai.plan(field).track)

    def test_starts_on_clear_ground_and_still_eats_everything(self) -> None:
        # Regression: the planner used to lay the snake down at the head of the cycle and
        # silently drop any target underneath it, which made "eats every contribution day"
        # false whenever a contribution landed on those cells.  It must instead choose a
        # clear stretch and eat all of them.
        targets = [(0, 0), (1, 0), (2, 0), (3, 0), (20, 3)]
        record = ai.plan(self._field(targets))
        self.assertEqual({(m.col, m.row) for m in record.meals}, set(targets))
        self._assert_run_is_valid(record)

    def test_every_target_is_eaten_exactly_once(self) -> None:
        targets = [(0, 0), (1, 0), (9, 2), (44, 5)]
        record = ai.plan(self._field(targets))
        eaten = [(m.col, m.row) for m in record.meals]
        self.assertEqual(len(eaten), len(set(eaten)))
        self.assertEqual(set(eaten), set(targets))


class RendererTests(unittest.TestCase):
    """Checks on the emitted SVG that do not need a browser.

    The browser checks (does it read as a snake, is the HUD legible at phone width) live in
    tools/shoot.py.  These cover the failure modes that are invisible either way.
    """

    def setUp(self) -> None:
        days = {
            "2026-03-02": 3, "2026-04-11": 1, "2026-05-20": 5,
            "2026-06-01": 2, "2026-07-14": 4, "2026-08-30": 1,
        }
        self.field = grid.build(_days(days), today=dt.date(2026, 9, 14))
        self.record = ai.plan(self.field)
        self.markup = render.render(self.record, self.field, _Discard())

    def test_is_well_formed_with_a_viewbox(self) -> None:
        root = ET.fromstring(self.markup)
        self.assertTrue(root.tag.endswith("svg"))
        self.assertTrue(root.get("viewBox"))

    def test_contains_no_smil_and_no_script(self) -> None:
        for banned in ("<animate", "<animateTransform", "<script", "xlink:href"):
            self.assertNotIn(banned, self.markup)

    def test_references_nothing_external(self) -> None:
        # Secure static mode drops remote references silently, so there must be none.
        self.assertNotIn("url(http", self.markup)
        self.assertNotIn("//fonts.", self.markup)

    def test_every_class_used_has_a_rule(self) -> None:
        declared = set(re.findall(r"\.([A-Za-z][\w-]*)\s*\{", self.markup))
        for value in set(re.findall(r'class="([^"]+)"', self.markup)):
            for name in value.split():
                self.assertIn(name, declared, f"class {name} has no rule")

    def test_has_no_duplicate_ids(self) -> None:
        ids = re.findall(r'\sid="([^"]+)"', self.markup)
        self.assertEqual(len(ids), len(set(ids)))

    def test_every_animation_shares_one_duration(self) -> None:
        # The sync guarantee: segments reading a shared track at different delays only line
        # up if every rule runs on the same clock.
        durations = set(re.findall(r"animation:[\w-]+ ([\d.]+)s", self.markup))
        self.assertEqual(len(durations), 1, f"durations diverged: {durations}")

    def test_segments_share_a_single_position_keyframe_block(self) -> None:
        """Every segment must read ONE shared path block at a different delay.

        This is the size lever the whole design rests on.  The renderer it replaces emitted
        a full keyframe block per segment -- O(segments x steps) -- and if that regresses the
        file grows by an order of magnitude while still looking and testing fine.
        """
        referenced = re.findall(r"animation:([\w-]+) ", self.markup)
        most_shared = collections.Counter(referenced).most_common(1)[0]
        self.assertGreaterEqual(
            most_shared[1],
            self.record.max_length,
            f"only {most_shared[1]} rules share a keyframe block, expected at least "
            f"{self.record.max_length} (one per segment)",
        )

    def test_stays_within_the_size_budget(self) -> None:
        self.assertLess(len(self.markup), 46 * 1024)

    def test_is_deterministic(self) -> None:
        again = render.render(self.record, self.field, _Discard())
        self.assertEqual(self.markup, again)


class _Discard:
    """A write-only stand-in so renderer tests never touch the filesystem."""

    def write_text(self, *args, **kwargs) -> None:
        return None


if __name__ == "__main__":
    unittest.main()
